server:
  port: 8083
spring:
  application:
    name: booking-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/booking_db}

# booking need to communicate with pricing service
app:
  pricing-service-url: ${APP_PRICING_SERVICE_URL:http://localhost:8082}