server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: resource-route
          uri: ${RESOURCE_URI:http://localhost:8081}
          predicates:
            - Path=/api/resources/**
        - id: pricing-route
          uri: ${PRICING_URI:http://localhost:8082}
          predicates:
            - Path=/api/pricing/**
            - Path=/api/seasons/**
        - id: booking-route
          uri: ${BOOKING_URI:http://localhost:8083}
          predicates:
            - Path=/api/bookings/**